curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs > src/main/specs/api_docs
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/system > src/main/specs/system
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/apikeytest > src/main/specs/apikeytest
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/app > src/main/specs/app
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/AzureStorage > src/main/specs/AzureStorage
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/db > src/main/specs/db
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/dfmongohq > src/main/specs/dfmongohq
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/DynamoDB > src/main/specs/DynamoDB
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/edmunds > src/main/specs/edmunds
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/email > src/main/specs/email
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/gtatest > src/main/specs/gtatest
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/mongo > src/main/specs/mongo
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/mongohq > src/main/specs/mongohq
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/mongohqry > src/main/specs/mongohqry
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/movies > src/main/specs/movies
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/mssql > src/main/specs/mssql
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/mssqlex > src/main/specs/mssqlex
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/portal > src/main/specs/portal
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/RFS_AWS > src/main/specs/RFS_AWS
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/rsFilesDFW > src/main/specs/rsFilesDFW
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/rsFilesORD > src/main/specs/rsFilesORD
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/salesforce > src/main/specs/salesforce
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/schema > src/main/specs/schema
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/sftest3 > src/main/specs/sftest3
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/sf_leetest2 > src/main/specs/sf_leetest2
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/SimpleDB > src/main/specs/SimpleDB
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/sqlazure > src/main/specs/sqlazure
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/support > src/main/specs/support
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/testWS > src/main/specs/testWS
curl -H "X-DreamFactory-Application-Name:todoangular" https://next.cloud.dreamfactory.com/rest/api_docs/weather > src/main/specs/weather
